### PR TITLE
Par stats

### PR DESCRIPTION
**Pull request by davidpng**
Please update error handling for cases that fail FCS load process/stat extraction

### CODE REVIEW

**Comment by hermands** [comment]
I need to merge this into master, check stats error handling, merge, and generate big stats db.

**Comment by davidpng** [comment]
How are you merging handle gates into this?  I have yet to check it

**Comment by hermands** [comment]
The how is easy.
The why is because I needed it's functionality.
Please check it whenever you have time.

...I'll pull par_stats back to you.

-Dan

**Comment by hermands** [comment]
I have:
-  added handling for stats extraction errors
- Changed multiprocessing such that can handle arguments (still have memory "leak")
- Added code from other branch that allows toggling off of singlet and viability gate

I am currently building stats using dev/test_make_statsdb.sh

Please evaluate and merge into master.

**Pull request merged**
